//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.20 at 03:15:22 PM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.bulstat.bg/GetStateOfPlayRequest", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package bg.infosys.daeu.ws.wsbg.regix.requests.bulstat;
