//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.03 at 03:39:23 PM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://egov.bg/RegiX/NRA/EmploymentContracts", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package bg.infosys.daeu.ws.wsbg.regix.nra;